name: build-and-push-caddy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * 1"   # weekly rebuild to track upstream latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: tingxueren/caddy-custom
  CADDY_IMAGE_VERSION: latest
  PLUGINS: >-
    --with github.com/mholt/caddy-l4
    --with github.com/caddyserver/forwardproxy
    --with github.com/mholt/caddy-webdav
    --with github.com/WeidiDeng/caddy-cloudflare-ip
    --with github.com/caddy-dns/cloudflare
    --with github.com/caddy-dns/duckdns
    --with github.com/caddy-dns/tencentcloud
    --with github.com/mholt/caddy-events-exec
    --with github.com/caddyserver/jsonc-adapter
    --with github.com/imgk/caddy-trojan

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{ is_default_branch }}
            type=sha,prefix=sha-,format=short
            type=raw,value=nightly,enable={{ is_schedule }}

      - name: Build and Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CADDY_IMAGE_VERSION=${{ env.CADDY_IMAGE_VERSION }}
            PLUGINS=${{ env.PLUGINS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
